// GENERATED by tool/gen_phosphor_catalog.py from Phosphor 2.1.1. Do not edit by hand:
// it scans lib/ for `PhIcons.<name>`, so add the reference and run it again.

part of 'app_icons.dart';

/// Phosphor glyphs referenced beyond [AppIcons] — the curated symbol set in
/// `icon_suggestions.dart` is where they are used. Generated from those
/// references, so tree-shaking keeps exactly the glyphs that are drawn.
abstract final class PhIcons {
  static const armchair = IconData(0xe013, fontFamily: _family);
  static const axe = IconData(0xe9fd, fontFamily: _family);
  static const babyCarriage = IconData(0xe819, fontFamily: _family);
  static const backpack = IconData(0xe923, fontFamily: _family);
  static const balloon = IconData(0xe76d, fontFamily: _family);
  static const bank = IconData(0xe0b5, fontFamily: _family);
  static const baseballCap = IconData(0xea29, fontFamily: _family);
  static const basketball = IconData(0xe725, fontFamily: _family);
  static const beanie = IconData(0xea2b, fontFamily: _family);
  static const belt = IconData(0xea2d, fontFamily: _family);
  static const binoculars = IconData(0xea65, fontFamily: _family);
  static const bird = IconData(0xe72d, fontFamily: _family);
  static const bone = IconData(0xe7f3, fontFamily: _family);
  static const boot = IconData(0xeccb, fontFamily: _family);
  static const bowlFood = IconData(0xeaa5, fontFamily: _family);
  static const bread = IconData(0xe81d, fontFamily: _family);
  static const broom = IconData(0xec55, fontFamily: _family);
  static const cactus = IconData(0xe919, fontFamily: _family);
  static const calculator = IconData(0xe539, fontFamily: _family);
  static const campfire = IconData(0xe9d9, fontFamily: _family);
  static const cat = IconData(0xe749, fontFamily: _family);
  static const chair = IconData(0xe951, fontFamily: _family);
  static const chalkboardTeacher = IconData(0xe601, fontFamily: _family);
  static const champagne = IconData(0xeacb, fontFamily: _family);
  static const clipboardText = IconData(0xe199, fontFamily: _family);
  static const cloudRain = IconData(0xe1b5, fontFamily: _family);
  static const coatHanger = IconData(0xe7ff, fontFamily: _family);
  static const coins = IconData(0xe78f, fontFamily: _family);
  static const compass = IconData(0xe1c9, fontFamily: _family);
  static const cookie = IconData(0xe6cb, fontFamily: _family);
  static const crown = IconData(0xe615, fontFamily: _family);
  static const desk = IconData(0xed17, fontFamily: _family);
  static const deviceTablet = IconData(0xe1e7, fontFamily: _family);
  static const diceFive = IconData(0xe1ef, fontFamily: _family);
  static const discoBall = IconData(0xed99, fontFamily: _family);
  static const dog = IconData(0xe74b, fontFamily: _family);
  static const dress = IconData(0xea7f, fontFamily: _family);
  static const dresser = IconData(0xe94f, fontFamily: _family);
  static const envelopeOpen = IconData(0xe217, fontFamily: _family);
  static const exam = IconData(0xe743, fontFamily: _family);
  static const faceMask = IconData(0xe56b, fontFamily: _family);
  static const fan = IconData(0xe9f3, fontFamily: _family);
  static const fireExtinguisher = IconData(0xe9e9, fontFamily: _family);
  static const firstAidKit = IconData(0xe571, fontFamily: _family);
  static const fish = IconData(0xe729, fontFamily: _family);
  static const flashlight = IconData(0xe247, fontFamily: _family);
  static const garage = IconData(0xecd7, fontFamily: _family);
  static const gasCan = IconData(0xe8cf, fontFamily: _family);
  static const globe = IconData(0xe289, fontFamily: _family);
  static const guitar = IconData(0xea8b, fontFamily: _family);
  static const hairDryer = IconData(0xea67, fontFamily: _family);
  static const hamburger = IconData(0xe791, fontFamily: _family);
  static const handHeart = IconData(0xe811, fontFamily: _family);
  static const handSoap = IconData(0xe631, fontFamily: _family);
  static const handbag = IconData(0xe29d, fontFamily: _family);
  static const hoodie = IconData(0xecd1, fontFamily: _family);
  static const identificationCard = IconData(0xe2c9, fontFamily: _family);
  static const keyboard = IconData(0xe2d9, fontFamily: _family);
  static const knife = IconData(0xe637, fontFamily: _family);
  static const ladder = IconData(0xe9e5, fontFamily: _family);
  static const lampPendant = IconData(0xee2f, fontFamily: _family);
  static const lego = IconData(0xe8c8, fontFamily: _family);
  static const lifebuoy = IconData(0xe63b, fontFamily: _family);
  static const lightbulb = IconData(0xe2dd, fontFamily: _family);
  static const lock = IconData(0xe2fb, fontFamily: _family);
  static const mapTrifold = IconData(0xe31b, fontFamily: _family);
  static const martini = IconData(0xe31d, fontFamily: _family);
  static const maskHappy = IconData(0xe9f5, fontFamily: _family);
  static const medal = IconData(0xe321, fontFamily: _family);
  static const moon = IconData(0xe331, fontFamily: _family);
  static const mountains = IconData(0xe7af, fontFamily: _family);
  static const mouse = IconData(0xe33b, fontFamily: _family);
  static const needle = IconData(0xe82f, fontFamily: _family);
  static const newspaper = IconData(0xe345, fontFamily: _family);
  static const notebook = IconData(0xe34f, fontFamily: _family);
  static const nut = IconData(0xe38d, fontFamily: _family);
  static const oven = IconData(0xed8d, fontFamily: _family);
  static const paintBrush = IconData(0xe6f1, fontFamily: _family);
  static const paintBucket = IconData(0xe393, fontFamily: _family);
  static const pants = IconData(0xec89, fontFamily: _family);
  static const paperclip = IconData(0xe39b, fontFamily: _family);
  static const pencil = IconData(0xe3af, fontFamily: _family);
  static const personSimpleHike = IconData(0xed55, fontFamily: _family);
  static const personSimpleRun = IconData(0xe731, fontFamily: _family);
  static const personSimpleSki = IconData(0xe71d, fontFamily: _family);
  static const personSimpleSwim = IconData(0xe737, fontFamily: _family);
  static const pianoKeys = IconData(0xe9c9, fontFamily: _family);
  static const picnicTable = IconData(0xee27, fontFamily: _family);
  static const piggyBank = IconData(0xea05, fontFamily: _family);
  static const pinwheel = IconData(0xeb9d, fontFamily: _family);
  static const pipeWrench = IconData(0xed89, fontFamily: _family);
  static const plugCharging = IconData(0xeb5d, fontFamily: _family);
  static const popcorn = IconData(0xeb4f, fontFamily: _family);
  static const pottedPlant = IconData(0xec23, fontFamily: _family);
  static const pushPin = IconData(0xe3e3, fontFamily: _family);
  static const puzzlePiece = IconData(0xe597, fontFamily: _family);
  static const rabbit = IconData(0xeac3, fontFamily: _family);
  static const rug = IconData(0xea1b, fontFamily: _family);
  static const sailboat = IconData(0xe78b, fontFamily: _family);
  static const seatbelt = IconData(0xedff, fontFamily: _family);
  static const shower = IconData(0xe777, fontFamily: _family);
  static const simCard = IconData(0xe665, fontFamily: _family);
  static const sneaker = IconData(0xe80d, fontFamily: _family);
  static const soccerBall = IconData(0xe717, fontFamily: _family);
  static const sock = IconData(0xeccf, fontFamily: _family);
  static const solarPanel = IconData(0xed7e, fontFamily: _family);
  static const speakerHifi = IconData(0xea09, fontFamily: _family);
  static const stamp = IconData(0xea49, fontFamily: _family);
  static const student = IconData(0xe73f, fontFamily: _family);
  static const sunglasses = IconData(0xe817, fontFamily: _family);
  static const teaBag = IconData(0xe8e7, fontFamily: _family);
  static const tennisBall = IconData(0xe721, fontFamily: _family);
  static const thermometer = IconData(0xe5c7, fontFamily: _family);
  static const ticket = IconData(0xe491, fontFamily: _family);
  static const tire = IconData(0xedd3, fontFamily: _family);
  static const toilet = IconData(0xe79b, fontFamily: _family);
  static const toiletPaper = IconData(0xe79d, fontFamily: _family);
  static const toolbox = IconData(0xeca1, fontFamily: _family);
  static const tooth = IconData(0xe9cd, fontFamily: _family);
  static const tote = IconData(0xe495, fontFamily: _family);
  static const towel = IconData(0xede7, fontFamily: _family);
  static const tray = IconData(0xe4ab, fontFamily: _family);
  static const treasureChest = IconData(0xede3, fontFamily: _family);
  static const trophy = IconData(0xe67f, fontFamily: _family);
  static const truck = IconData(0xe4b5, fontFamily: _family);
  static const usb = IconData(0xe957, fontFamily: _family);
  static const van = IconData(0xe827, fontFamily: _family);
  static const waves = IconData(0xe6df, fontFamily: _family);
  static const wifiHigh = IconData(0xe4eb, fontFamily: _family);
  static const yarn = IconData(0xed9b, fontFamily: _family);
}

/// The under-layer of each [PhIcons] glyph, by the over-layer's codepoint —
/// what [AppIcon] stacks beneath a glyph [AppIcons] does not name.
const Map<int, IconData> _phosphorUnderLayers = {
  0xe013: IconData(0xe012, fontFamily: _family),
  0xe9fd: IconData(0xe9fc, fontFamily: _family),
  0xe819: IconData(0xe818, fontFamily: _family),
  0xe923: IconData(0xe922, fontFamily: _family),
  0xe76d: IconData(0xe76c, fontFamily: _family),
  0xe0b5: IconData(0xe0b4, fontFamily: _family),
  0xea29: IconData(0xea28, fontFamily: _family),
  0xe725: IconData(0xe724, fontFamily: _family),
  0xea2b: IconData(0xea2a, fontFamily: _family),
  0xea2d: IconData(0xea2c, fontFamily: _family),
  0xea65: IconData(0xea64, fontFamily: _family),
  0xe72d: IconData(0xe72c, fontFamily: _family),
  0xe7f3: IconData(0xe7f2, fontFamily: _family),
  0xeccb: IconData(0xecca, fontFamily: _family),
  0xeaa5: IconData(0xeaa4, fontFamily: _family),
  0xe81d: IconData(0xe81c, fontFamily: _family),
  0xec55: IconData(0xec54, fontFamily: _family),
  0xe919: IconData(0xe918, fontFamily: _family),
  0xe539: IconData(0xe538, fontFamily: _family),
  0xe9d9: IconData(0xe9d8, fontFamily: _family),
  0xe749: IconData(0xe748, fontFamily: _family),
  0xe951: IconData(0xe950, fontFamily: _family),
  0xe601: IconData(0xe600, fontFamily: _family),
  0xeacb: IconData(0xeaca, fontFamily: _family),
  0xe199: IconData(0xe198, fontFamily: _family),
  0xe1b5: IconData(0xe1b4, fontFamily: _family),
  0xe7ff: IconData(0xe7fe, fontFamily: _family),
  0xe78f: IconData(0xe78e, fontFamily: _family),
  0xe1c9: IconData(0xe1c8, fontFamily: _family),
  0xe6cb: IconData(0xe6ca, fontFamily: _family),
  0xe615: IconData(0xe614, fontFamily: _family),
  0xed17: IconData(0xed16, fontFamily: _family),
  0xe1e7: IconData(0xe1e6, fontFamily: _family),
  0xe1ef: IconData(0xe1ee, fontFamily: _family),
  0xed99: IconData(0xed98, fontFamily: _family),
  0xe74b: IconData(0xe74a, fontFamily: _family),
  0xea7f: IconData(0xea7e, fontFamily: _family),
  0xe94f: IconData(0xe94e, fontFamily: _family),
  0xe217: IconData(0xe216, fontFamily: _family),
  0xe743: IconData(0xe742, fontFamily: _family),
  0xe56b: IconData(0xe56a, fontFamily: _family),
  0xe9f3: IconData(0xe9f2, fontFamily: _family),
  0xe9e9: IconData(0xe9e8, fontFamily: _family),
  0xe571: IconData(0xe570, fontFamily: _family),
  0xe729: IconData(0xe728, fontFamily: _family),
  0xe247: IconData(0xe246, fontFamily: _family),
  0xecd7: IconData(0xecd6, fontFamily: _family),
  0xe8cf: IconData(0xe8ce, fontFamily: _family),
  0xe289: IconData(0xe288, fontFamily: _family),
  0xea8b: IconData(0xea8a, fontFamily: _family),
  0xea67: IconData(0xea66, fontFamily: _family),
  0xe791: IconData(0xe790, fontFamily: _family),
  0xe811: IconData(0xe810, fontFamily: _family),
  0xe631: IconData(0xe630, fontFamily: _family),
  0xe29d: IconData(0xe29c, fontFamily: _family),
  0xecd1: IconData(0xecd0, fontFamily: _family),
  0xe2c9: IconData(0xe2c8, fontFamily: _family),
  0xe2d9: IconData(0xe2d8, fontFamily: _family),
  0xe637: IconData(0xe636, fontFamily: _family),
  0xe9e5: IconData(0xe9e4, fontFamily: _family),
  0xee2f: IconData(0xee2e, fontFamily: _family),
  0xe8c8: IconData(0xe8c6, fontFamily: _family),
  0xe63b: IconData(0xe63a, fontFamily: _family),
  0xe2dd: IconData(0xe2dc, fontFamily: _family),
  0xe2fb: IconData(0xe2fa, fontFamily: _family),
  0xe31b: IconData(0xe31a, fontFamily: _family),
  0xe31d: IconData(0xe31c, fontFamily: _family),
  0xe9f5: IconData(0xe9f4, fontFamily: _family),
  0xe321: IconData(0xe320, fontFamily: _family),
  0xe331: IconData(0xe330, fontFamily: _family),
  0xe7af: IconData(0xe7ae, fontFamily: _family),
  0xe33b: IconData(0xe33a, fontFamily: _family),
  0xe82f: IconData(0xe82e, fontFamily: _family),
  0xe345: IconData(0xe344, fontFamily: _family),
  0xe34f: IconData(0xe34e, fontFamily: _family),
  0xe38d: IconData(0xe38c, fontFamily: _family),
  0xed8d: IconData(0xed8c, fontFamily: _family),
  0xe6f1: IconData(0xe6f0, fontFamily: _family),
  0xe393: IconData(0xe392, fontFamily: _family),
  0xec89: IconData(0xec88, fontFamily: _family),
  0xe39b: IconData(0xe39a, fontFamily: _family),
  0xe3af: IconData(0xe3ae, fontFamily: _family),
  0xed55: IconData(0xed54, fontFamily: _family),
  0xe731: IconData(0xe730, fontFamily: _family),
  0xe71d: IconData(0xe71c, fontFamily: _family),
  0xe737: IconData(0xe736, fontFamily: _family),
  0xe9c9: IconData(0xe9c8, fontFamily: _family),
  0xee27: IconData(0xee26, fontFamily: _family),
  0xea05: IconData(0xea04, fontFamily: _family),
  0xeb9d: IconData(0xeb9c, fontFamily: _family),
  0xed89: IconData(0xed88, fontFamily: _family),
  0xeb5d: IconData(0xeb5c, fontFamily: _family),
  0xeb4f: IconData(0xeb4e, fontFamily: _family),
  0xec23: IconData(0xec22, fontFamily: _family),
  0xe3e3: IconData(0xe3e2, fontFamily: _family),
  0xe597: IconData(0xe596, fontFamily: _family),
  0xeac3: IconData(0xeac2, fontFamily: _family),
  0xea1b: IconData(0xea1a, fontFamily: _family),
  0xe78b: IconData(0xe78a, fontFamily: _family),
  0xedff: IconData(0xedfe, fontFamily: _family),
  0xe777: IconData(0xe776, fontFamily: _family),
  0xe665: IconData(0xe664, fontFamily: _family),
  0xe80d: IconData(0xe80c, fontFamily: _family),
  0xe717: IconData(0xe716, fontFamily: _family),
  0xeccf: IconData(0xecce, fontFamily: _family),
  0xed7e: IconData(0xed7a, fontFamily: _family),
  0xea09: IconData(0xea08, fontFamily: _family),
  0xea49: IconData(0xea48, fontFamily: _family),
  0xe73f: IconData(0xe73e, fontFamily: _family),
  0xe817: IconData(0xe816, fontFamily: _family),
  0xe8e7: IconData(0xe8e6, fontFamily: _family),
  0xe721: IconData(0xe720, fontFamily: _family),
  0xe5c7: IconData(0xe5c6, fontFamily: _family),
  0xe491: IconData(0xe490, fontFamily: _family),
  0xedd3: IconData(0xedd2, fontFamily: _family),
  0xe79b: IconData(0xe79a, fontFamily: _family),
  0xe79d: IconData(0xe79c, fontFamily: _family),
  0xeca1: IconData(0xeca0, fontFamily: _family),
  0xe9cd: IconData(0xe9cc, fontFamily: _family),
  0xe495: IconData(0xe494, fontFamily: _family),
  0xede7: IconData(0xede6, fontFamily: _family),
  0xe4ab: IconData(0xe4aa, fontFamily: _family),
  0xede3: IconData(0xede2, fontFamily: _family),
  0xe67f: IconData(0xe67e, fontFamily: _family),
  0xe4b5: IconData(0xe4b4, fontFamily: _family),
  0xe957: IconData(0xe956, fontFamily: _family),
  0xe827: IconData(0xe826, fontFamily: _family),
  0xe6df: IconData(0xe6de, fontFamily: _family),
  0xe4eb: IconData(0xe4ea, fontFamily: _family),
  0xed9b: IconData(0xed9a, fontFamily: _family),
};
