"""Write supabase/functions/_shared/abfall/upload_towns.ts from census_raw.json.

The towns of the providers we may not fetch from (`upload` in
abfall_providers.ts) whose town list the vendor only hands out live. Those
lists come from the last census, so resolving an address there never has to
ask the vendor: the household is told the town is served by upload and sent
to the file route. Single-town providers carry `town`/`cities` themselves and
are not listed here. Re-run after a census.
"""
import json, re, pathlib

HERE = pathlib.Path(__file__).parent
OUT = HERE / '../../supabase/functions/_shared/abfall/upload_towns.ts'
census = json.load(open(HERE / 'census_raw.json'))['providers']

def wanted(pid):
    return (pid.startswith('jumomind-') and not pid.startswith('jumomind-mymuell')) or pid == 'art-trier'

def names(towns):
    out = set(towns)
    # MyMüll-style "Gemeinde-Ortsteil" and "Gemeinde - Ortsteil": the geocoder
    # names the Gemeinde, so it is listed on its own too — but only where the
    # prefix really is a Gemeinde with parts ("Alsbach-Hähnlein" is one name).
    heads = {}
    for t in towns:
        m = re.match(r'^(.+?)\s+-\s+.+$', t)
        if m: out.add(m.group(1).strip()); continue
        m = re.match(r'^([^-]+)-(.+)$', t)
        if m: heads.setdefault(m.group(1).strip(), []).append(m.group(2).strip())
    for head, parts in heads.items():
        if len(parts) > 1 or head in parts: out.add(head)
    return sorted(out, key=lambda s: s.lower())

rows = {p['id']: names(p.get('towns') or []) for p in census if wanted(p['id'])}
lines = [
    '// abfall/upload_towns.ts — GENERATED by tool/abfall_census/gen_upload_towns.py',
    '// from the last census. Do not edit by hand; re-run the script instead.',
    '//',
    '// The towns of the upload-only providers whose town list the vendor hands',
    '// out only live (see `upload` in abfall_providers.ts). Kept here so that',
    '// recognising such a town never sends a request to a host we may not fetch.',
    '',
    'export const UPLOAD_TOWNS: Record<string, string[]> = {',
]
for pid in sorted(rows):
    lines.append(f'  {json.dumps(pid)}: {json.dumps(rows[pid], ensure_ascii=False)},')
lines += ['}', '']
OUT.write_text('\n'.join(lines))
print({k: len(v) for k, v in rows.items()})
