#!/usr/bin/env python3
"""Writes lib/theme/phosphor_catalog.dart: the `PhIcons` glyphs the code
references, with both duotone layers, from Phosphor's own published codepoints.

    python3 tool/gen_phosphor_catalog.py

Scans lib/ for `PhIcons.<camelName>` and generates exactly those, so adding a
symbol to `symbolGroups` costs one line there and one run of this, and the
release font keeps only what is drawn. Pinned to the release the vendored font
was cut from (its name table says "Version 2.1"); every codepoint is checked
against assets/icons/Phosphor-Duotone.ttf before it is written, so a typo or a
version drift fails here rather than drawing an empty box on a phone.
"""
import re
import struct
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERSION = "2.1.1"
CSS_URL = f"https://cdn.jsdelivr.net/npm/@phosphor-icons/web@{VERSION}/src/duotone/style.css"
FONT = ROOT / "assets/icons/Phosphor-Duotone.ttf"
OUT = ROOT / "lib/theme/phosphor_catalog.dart"
USAGE = re.compile(r"\bPhIcons\.([a-z][A-Za-z0-9]*)")


def kebab(camel):
    return re.sub(r"(?<=[a-z0-9])([A-Z])", r"-\1", camel).lower()


def font_codepoints(path):
    d = path.read_bytes()
    n = struct.unpack(">H", d[4:6])[0]
    tables = {}
    for i in range(n):
        tag, _, off, _ = struct.unpack(">4sIII", d[12 + 16 * i:28 + 16 * i])
        tables[tag] = off
    cmap = tables[b"cmap"]
    count = struct.unpack(">H", d[cmap + 2:cmap + 4])[0]
    cps = set()
    for i in range(count):
        _, _, sub = struct.unpack(">HHI", d[cmap + 4 + 8 * i:cmap + 12 + 8 * i])
        o = cmap + sub
        fmt = struct.unpack(">H", d[o:o + 2])[0]
        if fmt == 4:
            segx2 = struct.unpack(">H", d[o + 6:o + 8])[0]
            ends = struct.unpack(f">{segx2 // 2}H", d[o + 14:o + 14 + segx2])
            starts = struct.unpack(f">{segx2 // 2}H", d[o + 16 + segx2:o + 16 + 2 * segx2])
            for s, e in zip(starts, ends):
                if s != 0xFFFF:
                    cps.update(range(s, e + 1))
        elif fmt == 12:
            groups = struct.unpack(">I", d[o + 12:o + 16])[0]
            for g in range(groups):
                s, e, _ = struct.unpack(">III", d[o + 16 + 12 * g:o + 28 + 12 * g])
                cps.update(range(s, e + 1))
    return cps


def main():
    used = set()
    for path in (ROOT / "lib").rglob("*.dart"):
        if path != OUT:
            used.update(USAGE.findall(path.read_text(encoding="utf-8")))

    with urllib.request.urlopen(CSS_URL, timeout=60) as r:
        css = r.read().decode("utf-8")
    layers = {}
    for name, side, cp in re.findall(r'\.ph-duotone\.ph-([a-z0-9-]+):(before|after)\s*\{\s*content:\s*"\\([0-9a-f]+)"', css):
        layers.setdefault(name, {})[side] = int(cp, 16)
    if not layers:
        sys.exit("no codepoints parsed - the stylesheet format changed")

    in_font = font_codepoints(FONT)
    icons, missing = [], []
    for camel in sorted(used):
        pair = layers.get(kebab(camel), {})
        under, over = pair.get("before"), pair.get("after")
        if under is None or over is None:
            missing.append(f"PhIcons.{camel} ({kebab(camel)})")
            continue
        if under not in in_font or over not in in_font:
            sys.exit(f"{kebab(camel)}: {under:#x}/{over:#x} not in {FONT.name} - the font and {VERSION} disagree")
        icons.append((camel, under, over))
    if missing:
        sys.exit("no such Phosphor icon:\n  " + "\n  ".join(missing))

    lines = [
        f"// GENERATED by tool/gen_phosphor_catalog.py from Phosphor {VERSION}. Do not edit by hand:",
        "// it scans lib/ for `PhIcons.<name>`, so add the reference and run it again.",
        "",
        "part of 'app_icons.dart';",
        "",
        "/// Phosphor glyphs referenced beyond [AppIcons] — the curated symbol set in",
        "/// `icon_suggestions.dart` is where they are used. Generated from those",
        "/// references, so tree-shaking keeps exactly the glyphs that are drawn.",
        "abstract final class PhIcons {",
    ]
    lines += [f"  static const {camel} = IconData({over:#06x}, fontFamily: _family);" for camel, _, over in icons]
    lines += [
        "}",
        "",
        "/// The under-layer of each [PhIcons] glyph, by the over-layer's codepoint —",
        "/// what [AppIcon] stacks beneath a glyph [AppIcons] does not name.",
        "const Map<int, IconData> _phosphorUnderLayers = {",
    ]
    seen = set()
    for _, under, over in icons:
        if over not in seen:
            seen.add(over)
            lines.append(f"  {over:#06x}: IconData({under:#06x}, fontFamily: _family),")
    lines += ["};", ""]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(icons)} PhIcons -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
