// Copies the reviewed icons from `tool/icon_gen/out/` into `assets/grocery/`,
// downsized to the 512px the rest of the set uses, and prints the
// `GroceryIcon(...)` lines to paste into lib/data/grocery_catalog.dart.
//
//     dart run tool/icon_gen/install.dart --dry-run   # see what would move
//     dart run tool/icon_gen/install.dart
//
// Separate from generate.dart on purpose: generating is the step that costs
// money and sometimes misses, installing is the step that changes the app.
// Delete the misses from out/ first, then run this.
//
// The resize shells out to `sips`, which is part of macOS — no dependency, and
// the same tool that produced the existing set's dimensions.

import 'dart:convert';
import 'dart:io';

const _targetPx = 512;

Future<void> main(List<String> args) async {
  final dryRun = args.contains('--dry-run');
  if (args.any((a) => a != '--dry-run')) {
    stderr.writeln('usage: dart run tool/icon_gen/install.dart [--dry-run]');
    exit(64);
  }

  final root = _repoRoot();
  final outDir = Directory('${root.path}/tool/icon_gen/out');
  final assetDir = Directory('${root.path}/assets/grocery');

  if (!outDir.existsSync()) {
    stderr.writeln('Nothing generated yet — run generate.dart first.');
    exit(66);
  }

  final manifest = jsonDecode(
    File('${root.path}/tool/icon_gen/manifest.json').readAsStringSync(),
  ) as Map<String, dynamic>;
  final byFile = {
    for (final i in (manifest['items'] as List).cast<Map<String, dynamic>>())
      i['file'] as String: i,
  };

  final generated = outDir
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.png'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  if (generated.isEmpty) {
    stderr.writeln('tool/icon_gen/out/ has no PNGs in it.');
    exit(66);
  }

  final installed = <Map<String, dynamic>>[];
  final unknown = <String>[];

  for (final file in generated) {
    final name = file.uri.pathSegments.last;
    final item = byFile[name];
    if (item == null) {
      unknown.add(name);
      continue;
    }
    final target = '${assetDir.path}/$name';
    if (!dryRun) {
      file.copySync(target);
      final r = Process.runSync('sips', [
        '-Z', '$_targetPx', target,
        '-s', 'format', 'png',
        '--out', target,
      ]);
      if (r.exitCode != 0) {
        stderr.writeln('resize failed for $name: ${r.stderr}');
        exit(70);
      }
    }
    installed.add(item);
    stdout.writeln('${dryRun ? "would install" : "installed"}  $name');
  }

  if (unknown.isNotEmpty) {
    stdout.writeln('\nNot in the manifest, left alone:');
    for (final u in unknown) {
      stdout.writeln('  $u');
    }
  }

  if (installed.isEmpty) return;

  // The catalog lines, grouped by the category they belong in.
  final byCategory = <String, List<Map<String, dynamic>>>{};
  for (final i in installed) {
    byCategory.putIfAbsent(i['cat'] as String, () => []).add(i);
  }

  final buffer = StringBuffer()
    ..writeln('// Generated by tool/icon_gen/install.dart — paste into')
    ..writeln('// lib/data/grocery_catalog.dart, into the matching category.')
    ..writeln('//')
    ..writeln('// Three categories below are new: add them as whole')
    ..writeln('// GroceryCategory(...) blocks. The rest go inside categories')
    ..writeln('// that already exist.')
    ..writeln();

  const newCategories = {
    'Snacks & Knabbereien': 'Snacks',
    'Haushalt': 'Household',
    'Apotheke': 'Pharmacy & first aid',
  };

  for (final entry in byCategory.entries) {
    final isNew = newCategories.containsKey(entry.key);
    buffer.writeln(
      isNew
          ? "// NEW CATEGORY — wrap these in GroceryCategory('${entry.key}', '${newCategories[entry.key]}', [ ... ])"
          : '// into the existing ${entry.key} category',
    );
    for (final i in entry.value) {
      final alias = (i['alias'] as List).cast<String>();
      final aliasSrc =
          alias.isEmpty ? '' : ", [${alias.map((a) => "'${_esc(a)}'").join(', ')}]";
      buffer.writeln("    GroceryIcon('${i['file']}', '${_esc(i['de'] as String)}'$aliasSrc),");
    }
    buffer.writeln();
  }

  // Files whose English label the catalog cannot read off the name, because
  // their category's shared prefix does not cover them — see sharedFilePrefix.
  final overrides = installed.where((i) {
    final cat = i['cat'] as String;
    return cat == 'Getränke' || cat == 'Tierbedarf';
  }).toList();

  if (overrides.isNotEmpty) {
    buffer
      ..writeln('// Into _englishLabelOverrides — these two categories mix file')
      ..writeln('// prefixes, so sharedFilePrefix finds nothing to strip.');
    for (final i in overrides) {
      final stem = (i['file'] as String).replaceAll('.png', '');
      final label = stem.split('_').skip(i['cat'] == 'Getränke' ? 1 : 2).join(' ');
      final pretty = label.isEmpty
          ? stem
          : label[0].toUpperCase() + label.substring(1).toLowerCase();
      buffer.writeln("  '${i['file']}': '$pretty',");
    }
    buffer.writeln();
  }

  final linesFile = File('${root.path}/tool/icon_gen/catalog_lines.txt');
  if (!dryRun) linesFile.writeAsStringSync(buffer.toString());

  stdout.writeln('\n${installed.length} icon(s) ${dryRun ? "to install" : "installed"}.');
  stdout.writeln(dryRun
      ? '\n--dry-run: nothing copied.'
      : '\nCatalog lines written to tool/icon_gen/catalog_lines.txt\n'
          'Paste them into lib/data/grocery_catalog.dart, then:\n'
          '  flutter analyze\n'
          '  dart tool/check_const_palette.dart');
}

String _esc(String s) => s.replaceAll(r'\', r'\\').replaceAll("'", r"\'");

Directory _repoRoot() {
  var dir = Directory(Platform.script.toFilePath()).parent;
  while (!File('${dir.path}/pubspec.yaml').existsSync()) {
    final parent = dir.parent;
    if (parent.path == dir.path) {
      stderr.writeln('Could not find the repo root.');
      exit(70);
    }
    dir = parent;
  }
  return dir;
}
