"""Write supabase/functions/_shared/abfall/town_pages.ts from the atlas.

    python3 build_tracker.py <atlas.html>   # writes town_pages.json first
    python3 gen_town_pages.py

Every town no provider serves gets the official page where the town hands out
its calendar, and what that page offers (ics / pdf / html / app). The resolver
answers with it when nothing it may read serves the address, so the household
is sent to the town's own page and the upload instead of a dead end.

`town_key` and `town_head` MUST stay identical to `townKey`/`townHead` in
abfall/core.ts: the keys are computed here and looked up there.
"""
import json, re
from collections import defaultdict

CONNECTORS = {'a', 'am', 'an', 'der', 'die', 'dem', 'den', 'd', 'i', 'im', 'in', 'b', 'bei',
              'ob', 'o', 'v', 'vor', 'vd', 'u', 'und', 'zu', 'zum', 'zur'}
FMT = {'ics': 'ics', 'pdf_only': 'pdf', 'html_only': 'html', 'app_only': 'app'}


def tokens(name):
    s = name.lower().split(',')[0]
    s = re.sub(r'\([^)]*\)', ' ', s)
    out = [t for t in re.split(r'[\s./]+', s) if t]
    return ['sankt' if t == 'st' else t for t in out]


def town_key(name):
    return ' '.join(t for t in tokens(name) if t not in CONNECTORS)


def town_head(name):
    head = []
    for t in tokens(name):
        if t in CONNECTORS: break
        head.append(t)
    return ' '.join(head)


def main():
    reg = json.load(open('register.json'))
    kreise = {k['key']: k for k in reg['kreise']}
    pages = json.load(open('town_pages.json'))
    STATES = {'Schleswig-Holstein': 'SH', 'Hamburg': 'HH', 'Niedersachsen': 'NI', 'Bremen': 'HB',
              'Nordrhein-Westfalen': 'NW', 'Hessen': 'HE', 'Rheinland-Pfalz': 'RP',
              'Baden-Württemberg': 'BW', 'Bayern': 'BY', 'Saarland': 'SL', 'Berlin': 'BE',
              'Brandenburg': 'BB', 'Mecklenburg-Vorpommern': 'MV', 'Sachsen': 'SN',
              'Sachsen-Anhalt': 'ST', 'Thüringen': 'TH'}

    # How many towns of a state share a key or a head — over the whole register,
    # not just the unserved, so "Buch" never stands for "Buch a.Erlbach".
    key_n, head_n = defaultdict(int), defaultdict(int)
    for g in reg['gemeinden']:
        st = STATES[kreise[g['kreis']]['state']]
        key_n[(st, town_key(g['name']))] += 1
        head_n[(st, town_head(g['name']))] += 1

    # Index 0 is "no page": the town is still nobody's, so the household is sent
    # to the upload rather than to a dead end, but there is no link to give.
    urls, url_ix = [(None, None)], {(None, None): 0}
    keyed, headed = defaultdict(set), defaultdict(set)   # (st, key) -> {page index}
    key_hits, head_hits = defaultdict(int), defaultdict(int)
    dropped = defaultdict(int)
    for ars, p in pages.items():
        st = p['st']
        if not p.get('url') or p.get('check') is False or not p['url'].startswith('https://'):
            dropped['no working https page'] += 1
            entry = (None, None)
        else:
            entry = (p['url'], FMT.get(p.get('fmt')))
        if entry not in url_ix:
            url_ix[entry] = len(urls); urls.append(entry)
        ix = url_ix[entry]
        k, h = town_key(p['name']), town_head(p['name'])
        keyed[(st, k)].add(ix); key_hits[(st, k)] += 1
        if h and h != k:
            headed[(st, h)].add(ix); head_hits[(st, h)] += 1

    # A key is the atlas's only when every town of the state carrying it is in
    # the atlas — a "Neuhof" served by a vendor is not. Several pages under one
    # name ("Beuren" twice) is still nobody's town, just without a page.
    by_state = defaultdict(dict)
    for (st, k), ixs in keyed.items():
        if key_hits[(st, k)] != key_n[(st, k)]:
            dropped['name shared with a served town'] += key_hits[(st, k)]; continue
        by_state[st][k] = next(iter(ixs)) if len(ixs) == 1 else 0
        if len(ixs) > 1: dropped['several pages, no page given'] += key_hits[(st, k)]
    # The head alone ("Neumarkt" for "Neumarkt i.d.OPf.") on the same terms, and
    # only where no town is called just that.
    for (st, h), ixs in headed.items():
        if len(ixs) == 1 and head_hits[(st, h)] == head_n[(st, h)] and key_n[(st, h)] == 0:
            by_state[st].setdefault(h, next(iter(ixs)))

    out = ['// abfall/town_pages.ts — GENERATED by tool/abfall_authorities/gen_town_pages.py',
           '// from the Abfuhrkalender Atlas. Do not edit by hand; re-run the script instead.',
           '//',
           '// The official page of every town no provider serves, and what it hands out:',
           "// 'ics' a calendar file, 'pdf' a printable plan, 'html' dates on the page only,",
           "// 'app' only the town's app. Entry 0 is a town with no page to give. Keyed per",
           '// Bundesland by `townKey` (and `townHead` where that is unique), which is why',
           '// the key functions exist twice.',
           '',
           "export type TownPageFormat = 'ics' | 'pdf' | 'html' | 'app'",
           '',
           'export const TOWN_PAGE_URLS: Array<[string | null, TownPageFormat | null]> = [']
    out += [f'  [{json.dumps(u)}, {json.dumps(f)}],' for u, f in urls]
    out += [']', '', 'export const TOWN_PAGES: Record<string, Record<string, number>> = {']
    for st in sorted(by_state):
        items = ', '.join(f'{json.dumps(k, ensure_ascii=False)}: {v}' for k, v in sorted(by_state[st].items()))
        out.append(f'  {st}: {{ {items} }},')
    out += ['}', '']
    path = '../../supabase/functions/_shared/abfall/town_pages.ts'
    open(path, 'w').write('\n'.join(out))
    n = sum(len(v) for v in by_state.values())
    print(path, len(urls), 'pages,', n, 'keys;', dict(dropped))


if __name__ == '__main__':
    main()
