"""Collect the PDF calendars the atlas's pdf_only towns publish, into corpus/.

    python3 fetch_corpus.py            # fetch what is missing, rewrite manifest.json
    python3 fetch_corpus.py --offline  # only rewrite the manifest from what is on disk

Every distinct `fmt: pdf_only` page in ../abfall_authorities/town_pages.json is fetched once and
its PDF links that read like a bin calendar are downloaded to corpus/<sha1[:12]>.pdf. The PDFs
are gitignored (size, and they are the towns' documents, not ours); manifest.json is the record
of where each came from and which towns point at it, so the corpus can be rebuilt.

Needs requests + beautifulsoup4 (a venv is enough).
"""
import hashlib
import json
import os
import re
import sys
import time
from urllib.parse import urljoin

HERE = os.path.dirname(os.path.abspath(__file__))
PAGES = os.path.join(HERE, "..", "abfall_authorities", "town_pages.json")
CORPUS = os.path.join(HERE, "corpus")
MANIFEST = os.path.join(HERE, "manifest.json")
UA = {"User-Agent": "Mozilla/5.0 (Aporah Abfall PDF regression corpus)"}

# A link is worth downloading when its text or URL names a bin calendar, and not when it names
# the paperwork around one (fee schedules, forms, sorting guides).
WANT = re.compile(r"abfall|abfuhr|müll|muell|kalender|termin|202[5-8]|tonne|entsorg|tour|bezirk", re.I)
SKIP = re.compile(r"satzung|gebühr|gebuehr|antrag|formular|bestell|befreiung|sperrmüllkarte|abc|ratgeber|trennhilfe|wertstoffhof", re.I)
MAX_LINKS = 8


def load_pages():
    pages = json.load(open(PAGES))
    by_url = {}
    for ars, p in pages.items():
        if p.get("fmt") != "pdf_only" or not p.get("url"):
            continue
        e = by_url.setdefault(p["url"], {"page": p["url"], "publisher": p.get("publisher"), "towns": []})
        e["towns"].append({"ars": ars, "name": p.get("name"), "st": p.get("st")})
    return list(by_url.values())


def pdf_links(html, base):
    from bs4 import BeautifulSoup

    soup = BeautifulSoup(html, "html.parser")
    out = {}
    for a in soup.find_all("a", href=True):
        href = urljoin(base, a["href"])
        text = a.get_text(" ", strip=True)[:120]
        hay = f"{text} {href}"
        low = href.lower()
        if not (".pdf" in low or "download" in low or "fileadmin" in low):
            continue
        if WANT.search(hay) and not SKIP.search(hay):
            out.setdefault(href, text)
    return list(out.items())[:MAX_LINKS]


def main(offline=False):
    import requests

    os.makedirs(CORPUS, exist_ok=True)
    old = {}
    if os.path.exists(MANIFEST):
        for rec in json.load(open(MANIFEST))["pages"]:
            old[rec["page"]] = rec
    pages = load_pages()
    for i, rec in enumerate(pages):
        prev = old.get(rec["page"])
        if offline or (prev and prev.get("pdfs")):
            rec["pdfs"] = (prev or {}).get("pdfs", [])
            rec["error"] = (prev or {}).get("error")
            continue
        rec["pdfs"] = []
        try:
            r = requests.get(rec["page"], headers=UA, timeout=25)
            links = [(rec["page"], "")] if r.content[:4] == b"%PDF" else pdf_links(r.text, r.url)
            for href, text in links:
                try:
                    f = r if href == rec["page"] else requests.get(href, headers=UA, timeout=40)
                    if f.content[:4] != b"%PDF":
                        continue
                    sha = hashlib.sha1(f.content).hexdigest()[:12]
                    path = os.path.join(CORPUS, sha + ".pdf")
                    if not os.path.exists(path):
                        open(path, "wb").write(f.content)
                    rec["pdfs"].append({"id": sha, "url": href, "text": text, "bytes": len(f.content)})
                except Exception:
                    pass
                time.sleep(0.5)
        except Exception as e:
            rec["error"] = str(e)[:160]
        print(f"[{i + 1}/{len(pages)}] {len(rec['pdfs'])} pdf  {rec['page']}", file=sys.stderr)
    n = sum(len(p["pdfs"]) for p in pages)
    ids = {d["id"] for p in pages for d in p["pdfs"]}
    json.dump(
        {"note": "Generated by fetch_corpus.py. PDFs live in corpus/<id>.pdf (gitignored).",
         "pages": pages},
        open(MANIFEST, "w"), ensure_ascii=False, indent=1)
    print(f"{len(pages)} pages, {n} links, {len(ids)} distinct PDFs", file=sys.stderr)


if __name__ == "__main__":
    main(offline="--offline" in sys.argv)
